type hunterDatum = {
  nameJa: string;
  nameCn: string;
  nameEn: string;
  primaryNameJa: string;
  primaryNameCn: string;
  primaryNameEn: string;
  primaryCoolTime: number[];
  secondaryNameJa?: string;
  secondaryNameCn?: string;
  secondaryNameEn?: string;
  secondaryCoolTime?: number[];
  tertiaryNameJa?: string;
  tertiaryNameCn?: string;
  tertiaryNameEn?: string;
  tertiaryCoolTime?: number[];
};
export const hunterData: readonly hunterDatum[] = [
  {
    nameJa: "復讐者",
    nameCn: "厂长",
    nameEn: "Hell Ember",
    primaryNameJa: "黄パペット\n位置交換",
    primaryNameCn: "黄色傀儡\n位置交換",
    primaryNameEn: "Yellow\nPuppet",
    primaryCoolTime: [20],
    secondaryNameJa: "赤パペット\n位置交換",
    secondaryNameCn: "红色傀儡\n位置交換",
    secondaryNameEn: "Red\nPuppet",
    secondaryCoolTime: [20],
  },
  {
    nameJa: "道化師",
    nameCn: "小丑",
    nameEn: "Smiley Face",
    primaryNameJa: "ロケット\nダッシュ",
    primaryNameCn: "火箭冲刺",
    primaryNameEn: "Rocket Dash",
    primaryCoolTime: [12],
    secondaryNameJa: "ロケット\nダッシュ\n《抵抗》",
    secondaryNameCn: "火箭\n冲刺\n抗阻》",
    secondaryNameEn: 'Rocket Dash\n"Resistance"',
    secondaryCoolTime: [6],
  },
  {
    nameJa: "断罪狩人",
    nameCn: "鹿头",
    nameEn: "Gamekeeper",
    primaryNameJa: "チェーン\nクロウ",
    primaryNameCn: "荆棘链爪",
    primaryNameEn: "Chain Hook",
    primaryCoolTime: [14],
    secondaryNameJa: "トラバサミ",
    secondaryNameCn: "陷阱",
    secondaryNameEn: "Trap",
    secondaryCoolTime: [8, 5],
  },
  {
    nameJa: "リッパー",
    nameCn: "“杰克”",
    nameEn: "The Ripper",
    primaryNameJa: "寒霧",
    primaryNameCn: "寒雾",
    primaryNameEn: "Freezing Fog",
    primaryCoolTime: [20],
  },
  {
    nameJa: "結魂者",
    nameCn: "蜘蛛",
    nameEn: "Soul Weaver",
    primaryNameJa: "糸を吐く",
    primaryNameCn: "吐丝",
    primaryNameEn: "Spinning",
    primaryCoolTime: [10],
  },
  {
    nameJa: "芸者",
    nameCn: "红蝶",
    nameEn: "Geisha",
    primaryNameJa: "刹那生滅",
    primaryNameCn: "刹那生灭",
    primaryNameEn: "Dash Hit",
    primaryCoolTime: [8],
    secondaryNameJa: "アゲハ\nチャージ",
    secondaryNameCn: "使用蝴蝶",
    secondaryNameEn: "Butterfly\ncharge",
    secondaryCoolTime: [17],
  },
  {
    nameJa: "白黒無常",
    nameCn: "宿伞之魂",
    nameEn: "Wu Chang",
    primaryNameJa: "諸行無常",
    primaryNameCn: "诸行无常",
    primaryNameEn: "Summon",
    primaryCoolTime: [30],
    secondaryNameJa: "吸魂",
    secondaryNameCn: "摄魂",
    secondaryNameEn: "Siphon\nSoul",
    secondaryCoolTime: [5, 20],
    tertiaryNameJa: "揺魄",
    tertiaryNameCn: "荡魄",
    tertiaryNameEn: "Wavering\nSoul",
    tertiaryCoolTime: [15],
  },
  {
    nameJa: "写真家",
    nameCn: "摄影师",
    nameEn: "Photographer",
    primaryNameJa: "写真世界",
    primaryNameCn: "相中世界",
    primaryNameEn: "Camera\nWorld",
    primaryCoolTime: [60, 45],
    secondaryNameJa: "痕跡記録",
    secondaryNameCn: "瞬影留痕",
    secondaryNameEn: "move record",
    secondaryCoolTime: [15],
  },
  {
    nameJa: "狂眼",
    nameCn: "疯眼",
    nameEn: "Mad Eyes",
    primaryNameJa: "仕掛け壁\n消失",
    primaryNameCn: "围栏消失",
    primaryNameEn: "fence\ndisap-\npearance",
    primaryCoolTime: [40],
    secondaryNameJa: "未解読\n暗号機\n付近",
    secondaryNameCn: "附近的\n未解码\n机关控制台",
    secondaryNameEn: "nearby\nundecoded\nMachines",
    secondaryCoolTime: [20],
    tertiaryNameJa: "オーバー\nクロック",
    tertiaryNameCn: "超频",
    tertiaryNameEn: "Overclock",
    tertiaryCoolTime: [10, 20],
  },
  {
    nameJa: "黄衣の王",
    nameCn: "黄衣之主",
    nameEn: "The Feaster",
    primaryNameJa: "悪夢浸蝕",
    primaryNameCn: "噩梦侵袭",
    primaryNameEn: "Nightmare\nAttack",
    primaryCoolTime: [5],
    secondaryNameJa: "悪夢凝視",
    secondaryNameCn: "噩梦凝视",
    secondaryNameEn: "Nightmare\nGaze",
    secondaryCoolTime: [20, 5],
  },
  {
    nameJa: "夢の魔女",
    nameCn: "梦之女巫",
    nameEn: "Dream Witch",
    primaryNameJa: "寄生\n（存在感０）",
    primaryNameCn: "寄生\n（存在感０）",
    primaryNameEn: "Leech\n(presence 0)",
    primaryCoolTime: [75], // オリジナル信者（寄生信者は含まない）で殴るたびにクールタイムが40%短くなる（例えば残り時間が60秒のときに殴れば残り時間が60×0.6=36秒になる）
    secondaryNameJa: "同化\n（存在感１）",
    secondaryNameCn: "同化\n（存在感１）",
    secondaryNameEn: "Assimilation\n(presence 1)",
    secondaryCoolTime: [45], // 上に同じ
  },
  {
    nameJa: "泣き虫",
    nameCn: "爱哭鬼",
    nameEn: "Axe Boy",
    primaryNameJa: "怨霊消滅",
    primaryNameCn: "除怨",
    primaryNameEn: "Dispel\nSouls",
    primaryCoolTime: [15],
    secondaryNameJa: "怨霊の\n巡回",
    secondaryNameCn: "消失的怨灵",
    secondaryNameEn: "Resentful\nSouls\nrevolving",
    secondaryCoolTime: [30],
    tertiaryNameJa: "安息の道",
    tertiaryNameCn: "安息之路",
    tertiaryNameEn: "Restful\nRoad",
    tertiaryCoolTime: [18],
  },
  {
    nameJa: "魔トカゲ",
    nameCn: "孽蜥",
    nameEn: "Evil Reptilian",
    primaryNameJa: "ハンタージャンプ",
    primaryNameCn: "猎食之跃",
    primaryNameEn: "Preying Leap",
    primaryCoolTime: [11],
  },
  {
    nameJa: "血の女王",
    nameCn: "红夫人",
    nameEn: "Bloody Queen",
    primaryNameJa: "鏡影",
    primaryNameCn: "镜影",
    primaryNameEn: "Mirror Image",
    primaryCoolTime: [13, 15],
  },
  {
    nameJa: "ガードNo.26",
    nameCn: "26号守卫",
    nameEn: "Guard 26",
    primaryNameJa: "リモコン爆弾",
    primaryNameCn: "遥控炸弹",
    primaryNameEn: "Remote-Controlled Bomb",
    primaryCoolTime: [40, 35],
  },
  {
    nameJa: "｢使徒｣",
    nameCn: "“使徒”",
    nameEn: '"Disciple"',
    primaryNameJa: "急襲",
    primaryNameCn: "扑袭",
    primaryNameEn: "Swoop",
    primaryCoolTime: [10],
    secondaryNameJa: "ランウェイ",
    secondaryNameCn: "猫步",
    secondaryNameEn: "Catwalk",
    secondaryCoolTime: [16],
  },
  {
    nameJa: "ヴァイオリニスト",
    nameCn: "小提琴家",
    nameEn: "Violinist",
    primaryNameJa: "奏鳴曲",
    primaryNameCn: "奏鸣曲",
    primaryNameEn: "Sonata",
    primaryCoolTime: [13],
    secondaryNameJa: "狂想曲",
    secondaryNameCn: "狂想曲",
    secondaryNameEn: "Rhapsody",
    secondaryCoolTime: [9, 14],
  },
  {
    nameJa: "彫刻師",
    nameCn: "雕刻家",
    nameEn: "Sculptor",
    primaryNameJa: "彫像\nチャージ",
    primaryNameCn: "消耗雕像",
    primaryNameEn: "Sculptures\ncharge",
    primaryCoolTime: [16],
    secondaryNameJa: "象形墓場",
    secondaryNameCn: "象形坟场",
    secondaryNameEn: "Hieroglyphic\nGraveyard",
    secondaryCoolTime: [12, 15],
  },
  {
    nameJa: "｢アンデッド｣",
    nameCn: "“博士”",
    nameEn: '"Undead"',
    primaryNameJa: "溜め重叩き",
    primaryNameCn: "重击",
    primaryNameEn: "Charged\nStrike",
    primaryCoolTime: [14],
    secondaryNameJa: "エネルギー\n変換",
    secondaryNameCn: "能量转换",
    secondaryNameEn: "Energy\nConversion",
    secondaryCoolTime: [35],
  },
  {
    nameJa: "破輪",
    nameCn: "破轮",
    nameEn: "The Breaking Wheel",
    primaryNameJa: "悲観",
    primaryNameCn: "悲观",
    primaryNameEn: "Pessimistic",
    primaryCoolTime: [32],
    secondaryNameJa: "突刺の輪",
    secondaryNameCn: "穿刺之轮",
    secondaryNameEn: "Wheel of\nImpalement",
    secondaryCoolTime: [6, 14],
    tertiaryNameJa: "道化",
    tertiaryNameEn: "Ridicule",
    tertiaryCoolTime: [30],
  },
  {
    nameJa: "漁師",
    nameCn: "渔女",
    nameEn: "Naiad",
    primaryNameJa: "漁狩",
    primaryNameCn: "渔猎",
    primaryNameEn: "Spearfishing",
    primaryCoolTime: [19, 9],
    secondaryNameJa: "驚波",
    secondaryNameCn: "惊波",
    secondaryNameEn: "Surging\nTides",
    secondaryCoolTime: [15],
  },
  {
    nameJa: "蝋人形師",
    nameCn: "蜡像师",
    nameEn: "Wax Artist",
    primaryNameJa: "蝋付着\n操作不能\n時間",
    primaryNameCn: "被禁锢",
    primaryNameEn: "Wax-coated\nunusable\ntime",
    primaryCoolTime: [15],
    secondaryNameJa: "硬化",
    secondaryNameCn: "凝蜡",
    secondaryNameEn: "Solid Wax",
    secondaryCoolTime: [18],
    tertiaryNameJa: "熔蝋",
    tertiaryNameCn: "熔蜡",
    tertiaryNameEn: "Molten Wax",
    tertiaryCoolTime: [25, 25],
  },
  {
    nameJa: "｢悪夢｣",
    nameCn: "“噩梦”",
    nameEn: '"Nightmare"',
    primaryNameJa: "渡鴉",
    primaryNameCn: "渡鸦",
    primaryNameEn: "Raven",
    primaryCoolTime: [20],
    secondaryNameJa: "凶兆",
    secondaryNameCn: "噩兆",
    secondaryNameEn: "Bad Omen",
    secondaryCoolTime: [50],
  },
  {
    nameJa: "書記官",
    nameCn: "记录员",
    nameEn: "Clerk",
    primaryNameJa: "審査",
    primaryNameCn: "审阅",
    primaryNameEn: "Inspect",
    primaryCoolTime: [6, 6],
    secondaryNameJa: "記録・無効",
    secondaryNameCn: "无效",
    secondaryNameEn: "Record\n& Invalid",
    secondaryCoolTime: [10, 9],
  },
  {
    nameJa: "隠者",
    nameCn: "隐士",
    nameEn: "Hermit",
    primaryNameJa: "奇跡",
    primaryNameCn: "奇迹",
    primaryNameEn: "Miracle",
    primaryCoolTime: [12],
    secondaryNameJa: "感知",
    secondaryNameCn: "感知",
    secondaryNameEn: "Meditation",
    secondaryCoolTime: [60],
    tertiaryNameJa: "寄託",
    tertiaryNameCn: "寄托",
    tertiaryNameEn: "Attachment",
    tertiaryCoolTime: [40],
  },
  {
    nameJa: "夜の番人",
    nameCn: "守夜人",
    nameEn: "Night Watch",
    primaryNameJa: "風域",
    primaryNameCn: "风域",
    primaryNameEn: "Tempest",
    primaryCoolTime: [13],
    secondaryNameJa: "風行",
    secondaryNameCn: "风行",
    secondaryNameEn: "WindWalk",
    secondaryCoolTime: [5],
  },
  {
    nameJa: "オペラ歌手",
    nameCn: "歌剧演员",
    nameEn: "Opera Singer",
    primaryNameJa: "暗影の\n跳躍",
    primaryNameCn: "暗影之跃",
    primaryNameEn: "Shadow\nLeap",
    primaryCoolTime: [8],
    secondaryNameJa: "影の追想",
    secondaryNameCn: "影之回溯",
    secondaryNameEn: "Shadow\nDance",
    secondaryCoolTime: [20],
    tertiaryNameJa: "影襲",
    tertiaryNameCn: "影袭",
    tertiaryNameEn: "Shadow-\nstrike",
    tertiaryCoolTime: [15, 5],
  },
  {
    nameJa: "「フールズ・ゴールド」",
    nameCn: "“愚人金”",
    nameEn: '"Fool\'s Gold"',
    primaryNameJa: "不安定\nエリア",
    primaryNameCn: "不稳定区域",
    primaryNameEn: "Unstable\nGround",
    primaryCoolTime: [22],
    secondaryNameJa: "磁力変換",
    secondaryNameCn: "磁性转化",
    secondaryNameEn: "Magnetic\nConversion",
    secondaryCoolTime: [20, 5],
    tertiaryNameJa: "一触即発",
    tertiaryNameCn: "一触即发",
    tertiaryNameEn: "Instant\nReaction",
    tertiaryCoolTime: [20],
  },
  {
    nameJa: "時空の影",
    nameCn: "时空之影",
    nameEn: "The shadow",
    primaryNameJa: "古の面",
    primaryNameCn: "远古之面",
    primaryNameEn: "Ancient\nVisage",
    primaryCoolTime: [15],
    secondaryNameJa: "憑依(第\n1スキル\n解放後)",
    secondaryNameCn: "寄宿(1阶)",
    secondaryNameEn: "infection\n(1st skill\nunlocked)",
    secondaryCoolTime: [38],
    tertiaryNameJa: "空間転送",
    tertiaryNameCn: "空间传送",
    tertiaryNameEn: "Inter-\ndimensional\nTravel",
    tertiaryCoolTime: [45],
  },
];
